name: Continuous integration - msbuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level (not active)'
        required: true
        default: 'warning'

jobs:

  build:
    name: "Continuous integration - ms build"
    # 26.11.2021:
    # - windows-latest uses VS2019
    # - windows-2022 uses VS20222
    runs-on: windows-2022
    steps:
    - name: Parameters
      run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install framework 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install framework 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install framework 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Add MSBuild to path
      uses: microsoft/setup-msbuild@v1.1
      #with:
      #  vs-version: '[17.0,17.0]'
    - name: Add nuget to path
      uses: nuget/setup-nuget@v1
    - name: Restore packages (msbuild)
      run: msbuild -t:restore Sources\PDFiumDotNET.sln
    - name: Restore packages (nuget)
      run: nuget restore Sources\PDFiumDotNET.sln
    - name: Build solution
      run: msbuild -t:build -property:Configuration=Release Sources\PDFiumDotNET.sln
    - name: Unit test for PDFiumDotNET.Wrapper
      run: dotnet test Sources\Wrapper\Wrapper.Test\PDFiumDotNET.Wrapper.Test.csproj
    - name: Unit test for PDFiumDotNET.Components
      run: dotnet test Sources\Components\Components.Test\PDFiumDotNET.Components.Test.csproj
