name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level (not active)'
        required: true
        default: 'warning'

# comment to 'runs-on'
#   - windows-latest uses VS2019
#   - windows-2022 uses VS2022

jobs:

  build-debug:
    name: "DEBUG"
    runs-on: windows-2022
    steps:
    - name: Parameters
      run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install framework 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'
    - name: Install framework 5.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'
    - name: Install framework 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install framework 7.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'
    - name: Restore dependencies specified in a .NET projects.
      run: dotnet restore ./Sources/PDFiumDotNET.sln
    - name: Build all .NET projects.
      run: dotnet build -c DEBUG ./Sources/PDFiumDotNET.sln
    - name: Run unit tests using the test runner specified in a .NET projects.
      run: dotnet test -c DEBUG ./Sources/PDFiumDotNET.sln

  build-release:
    name: "RELEASE"
    runs-on: windows-2022
    steps:
    - name: Parameters
      run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install framework 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'
    - name: Install framework 5.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'
    - name: Install framework 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install framework 7.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'
    - name: Restore dependencies specified in a .NET projects.
      run: dotnet restore ./Sources/PDFiumDotNET.sln
    - name: Build all .NET projects.
      run: dotnet build -c RELEASE ./Sources/PDFiumDotNET.sln
    - name: Run unit tests using the test runner specified in a .NET projects.
      run: dotnet test -c RELEASE ./Sources/PDFiumDotNET.sln
